const express = require('express')
const router = express.Router()
const adminController = require('../app/controllers/adminController')
const upload = require('../app/middleware/cloudinary');

router.get('/', adminController.show)
router.get('/all-customers', adminController.allCustomers)
router.get('/all-customers/:id', adminController.customerInfo)
router.get('/create/customer', adminController.createCustomer)
router.post('/customer/created', adminController.customerCreated)
router.get('/all-orders', adminController.allOrders)
router.get('/all-orders/:id', adminController.orderInfo)
router.put('/order-updated/:id', adminController.orderUpdated)
router.get('/all-stores', adminController.allStores)
router.get('/all-brands', adminController.allStores)
router.get('/create/product', adminController.createProduct)
router.post('/product/created', upload.single('img'), adminController.productCreated)
router.get('/all-products', adminController.allProducts)
router.get('/updating/:id', adminController.updatingProduct)
router.put('/updated/:id', upload.single('img'), adminController.productUpdated)
router.delete('/soft-delete/:id', adminController.softDelete)
router.delete('/delete/:id', adminController.deleteProduct)
router.get('/restore/:id', adminController.restore)
router.get('/trash', adminController.trash)
router.get('/update-profile/:id', adminController.updateProfile)
router.put('/profile-updated/:id', adminController.profileUpdated)

module.exports = router